version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: sipena-database
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - sipena_db_volume:/var/lib/postgresql/data
  
  

volumes:
  sipena_db_volume:
    driver: local